import React, { Component } from "react";
import chiro2 from "../images/chir02.png";
import chiro1 from "../images/chiro1.jpg";
import chiro3 from "../images/chrio3.jpg";
class service extends Component {
  render() {
    return (
      <div>
        <h3 style={{ textAlign: "left", paddingLeft: "10px" }}>
          Service/Benefits
        </h3>

        <div
          className=" card bg-light mr-5 ml-5 mt-5 md-5"
          
        >
          <h2>Chiropractic Care</h2>
          <img className="img2" src={chiro1} style={{ float: "left" }} />
          Chiropractic care utilizes manual manipulation of the spine to restore
          the normal movement and position of the spinal vertebrae. It is by
          far, the single-most effective treatment for minimizing the long-term
          impact of whiplash injuries, especially when coupled with massage
          therapy, trigger point therapy, exercise rehabilitation and other soft
          tissue rehabilitation modalities.
        </div>

        <div
          className="card bg-light mr-5 ml-5 mt-5 md-5"
          style={{
            paddingTop: "30px",
            content: "",
            clear: "both",
            display: "table"
          }}
        >
          <h2>Physical Therapy/Physiotherapy</h2>
          <img className="img2" src={chiro2} style={{ float: "right" }} />
          <ul style={{ listStyleType: "none" }}>
            <li>
              Is primarily concerned with the remediation of impairments,
              disabilities, and the promotion of mobility. Focusing on
              functional ability, quality of life and movement potential through
              examination, evaluation, diagnosis and physical intervention.
            </li>
            <li>
              Electric Muscle Stimulation- Is the elicitation of muscle
              contraction using electric impulses. The impulses are generated by
              a device and delivered through electrodes on the skin in direct
              proximity to the muscles to be stimulated. The impulses mimic the
              action potential coming from the central nervous system, causing
              the muscle to contract. The electrodes are generally pads that
              adhere to the skin. This procedure increases red blood flow, which
              carries oxygen to heal tissue and swelling.
            </li>
          </ul>
        </div>

        <div
          className="card bg-light mr-5 ml-5 mt-5 md-5"
          stlye={{ content: "", clear: "both", display: "table",margin: '25px 50px 75px 100px' }}
        >
          <h2>Therapy Service</h2>
          <img className="img2" src={chiro3} style={{ float: "left" }} />
          <ul style={{ listStyleType: "none" }}>
            <li>
              Cryotherapy- Is used to treat acute soft tissue injuries. Various
              methods include ice packs, ice towels, ice massage, gel packs,
              refrigerant gases and inflatable splints.
              <br />Hydrotherapy- is a method that involves the use of hot water
              pain relief and treatment. The term encompasses a broad range of
              approaches and therapeutic methods that take advantage of the
              physical properties of water, such as temperature and pressure,
              for therapeutic purposes, to stimulate blood circulation and treat
              the symptoms of an accident.
              <br />Ultrasound- is a procedure that stimulates the tissue
              beneath the skins surface using very high frequency sound waves.
              Using a transducer or applicator that is in direct contact with
              the patient’s skin, Gel is used on all surfaces of the head to
              reduce friction and assist transmission of the ultrasonic waves.
              Theses waves are absorbed primarily by connective tissue,
              ligaments, tendons, and fascia
            </li>
          </ul>
        </div>
      </div>
    );
  }
}

export default service;
